version: '3'
services:
  presidio-anonymizer:
    build:
      context: ./presidio-anonymizer
      args:
        - NAME=presidio-anonymizer
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
